name: Docker - Downloader

on:
  push:
    tags: ['*.*.*']
    branches: ['*']
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/docker-build.yml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      component: downloader
      dockerfile: build/package/downloader/Dockerfile
      platforms: linux/amd64,linux/arm64
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
