name: Docker - Downloader

on:
  push:
    tags: ['*.*.*']
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/docker-build.yml
    with:
      component: downloader
      dockerfile: build/package/downloader/Dockerfile
      platforms: linux/amd64
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
