name: Progger - DMG Build

on:
  workflow_dispatch:

env:
  PDFIUM_VERSION: "6406"
  PDFIUM_OS: "ios-arm64"

jobs:
  build-dmg:
    env:
      CGO_ENABLED: 1
      LD_LIBRARY_PATH: "/opt/pdfium/lib"
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.work'
          cache-dependency-path: go.work.sum
      - name: Set up PDFium library
        run: |
          curl -L https://github.com/bblanchon/pdfium-binaries/releases/download/chromium%2F${{ env.PDFIUM_VERSION }}/pdfium-${{ env.PDFIUM_OS }}.tgz -o pdfium-${{ env.PDFIUM_OS }}.tgz
          sudo mkdir -p /usr/local/lib
          sudo mkdir /opt/pdfium && sudo tar -C /opt/pdfium -xvf pdfium-${{ env.PDFIUM_OS }}.tgz
          sudo rm pdfium-${{ env.PDFIUM_OS }}.tgz
#          sudo cp ./.github/workflows/pdfium.pc /usr/lib/pkgconfig/pdfium.pc
#      - name: Build
#        uses: crazy-max/ghaction-xgo@v3
#        with:
#          xgo_version: latest
#          go_version: 1.21
#          dest: build
#          prefix: progger
#          targets: darwin/arm64
#          pkg: exporter/cmd/exporter.go
#          v: true
#          x: false
#          race: false
#          ldflags: -s -w
#          buildmode: default
#          trimpath: true
#      - uses: actions/upload-artifact@v4
#        with:
#          name: progger-bin
#          path: progger